### ISSUE TITLE
Hangs on Windows/Webstorm

### ISSUE THREAD

**Issue by bebraw** [sturdynut/git-prepush-hook#3]
A user reported the prepush hook hangs on Windows if you are using Webstorm. See https://github.com/reactabular/column-extensions/pull/4#issuecomment-277486410 .

It probably has to do with the fact that this is a bash tool underneath. Maybe it would be good to skip the logic if a wrong environment is detected?

CC @gkedge

**Comment by sturdynut** [comment]
I'll take a look, thanks @bebraw

**Comment by bebraw** [comment]
FYI, [pre-git](https://www.npmjs.com/package/pre-git) has solved it so that might be worth a look.

**Comment by sturdynut** [comment]
@bebraw - Can you try again?  I took a shot gun approach and wrapped the install in a try/catch.  I published version 1.0.2 with this change, so have a look and if you are still having trouble I'll dig more into it.  Cheers.

**Comment by bebraw** [comment]
Thanks. I poked the user that did the original report. Let's hope he comments here about the results.

**Comment by gkedge** [comment]
I have been "poked"!  It still hangs just after @bebraw's `npm test:all` script starts.  Specifically, I am running in the bash shell that https://git-scm.com/ provides for Windoze installs.  But, the behavior is the same in `cmd`.  

@bebraw's `test:all` is executing both `jest` and `eslint`:
```
  "scripts": {
    "test:all": "npm test && npm run test:lint",
    "test": "jest --",
    "test:coverage": "jest --coverage --",
    "test:lint": "eslint . --ext .js --cache",
    "test:watch": "jest --watch --",
    "dist:build": "rimraf ./dist && babel ./src --out-dir ./dist",
    "preversion": "npm run test:all && npm run dist:build && git commit --allow-empty -am \"Update dist\""
  },
```

**Comment by sturdynut** [comment]
@bebraw - I see you closed out the [issue](https://github.com/reactabular/column-extensions/pull/4#issuecomment-277486410) from your comment, is it safe to close this?  @gkedge?

Not sure if you have tried them, but [Husky](https://github.com/typicode/husky) or [gHooks](https://github.com/gtramontina/ghooks) might be able to provide more robust functionality for managing your git hooks.  This library only adds in your pre-push hook.

**Comment by bebraw** [comment]
@sturdynut The issue was related to something else.

Let's close. If a wild Windows user appears, they can open a new issue.
